### ISSUE TITLE
Cannot build with `megaparsec` 9

### ISSUE THREAD

**Issue by ocharles** [archambaultv/sexpresso#9]
```
src/Data/SExpresso/Parse/Location.hs:47:12: error:
    • Could not deduce (TraversableStream s)
        arising from a use of ‘getSourcePos’
      from the context: MonadParsec e s m
        bound by the type signature for:
                   located :: forall e s (m :: * -> *) a.
                              MonadParsec e s m =>
                              m a -> m (Located a)
        at src/Data/SExpresso/Parse/Location.hs:45:1-54
      Possible fix:
        add (TraversableStream s) to the context of
          the type signature for:
            located :: forall e s (m :: * -> *) a.
                       MonadParsec e s m =>
                       m a -> m (Located a)
    • In a stmt of a 'do' block: begin <- getSourcePos
      In the expression:
        do begin <- getSourcePos
           result <- parser
           end <- getSourcePos
           return $ At (Span begin end) result
      In an equation for ‘located’:
          located parser
            = do begin <- getSourcePos
                 result <- parser
                 end <- getSourcePos
                 ....
   |
47 |   begin <- getSourcePos
   |
```

**Comment by archambaultv** [comment]
Hi. Thanks for reporting this. 
I will look into this issue hopefully by the end of next week. Sorry for the delay I am quite busy this week.

**Comment by archambaultv** [comment]
Sexpresso now builds with stack its 18.10 and this is fixed. Commit 4f225229d665626d3f733818d349010ee4f603d3.
I will push version 1.2.0.0 to Hackage.
